---
- name: Install HAProxy
  apt:
    name: haproxy
    state: present
  become: true

- name: Configure HAProxy for Redis
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy

- name: Enable and start HAProxy
  systemd:
    name: haproxy
    state: restarted
    enabled: yes
  become: true