---
- name: Configure Redis Sentinel
  template:
    src: sentinel.conf.j2
    dest: "/etc/redis/sentinel.conf"
  notify:
    - restart sentinel

- name: Ensure Sentinel is running
  systemd:
    name: redis-sentinel
    state: started
    enabled: yes
  become: true