# Hosted zone
domain: example.com


# Default ports which will be used with cluster/service specific offset
redis_port: 36379
sentinel_port: 26379
haproxy_api_port: 9899
haproxy_redis_local_port: 46379
haproxy_redis_local_ssl_port: 56379
haproxy_redis_ssl_port: 6379
haproxy_sentinel_ssl_port: 16379


# Cluster > subcluster > instance.
# DNS: <subcluster>N.<cluster>.example.com. Example: redisdb1.testcluster1.example.com
# All subcluster names should start with "redisdb". Default subcluster name is redisdb.
instances:
  testcluster1:
    redisdb-mytest:
      srv1: 10.0.7.72
      srv2: 10.0.7.142
      srv3: 10.0.7.202

