---
- name: restart redis
  systemd:
    name: redis@{{ item }}
    state: restarted
  with_items: "{{ redis_ports }}"
  become: true

- name: restart sentinel
  systemd:
    name: redis-sentinel
    state: restarted
  become: true

- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
  become: true